export * from './auth';
export * from './user';
export * from './university';
export * from './major';
export * from './group';
export * from './attendance';
export * from './subject';
export * from './registerData'
export * from './occasions';
export * from './period';
export * from './classroom';