apiVersion: apps/v1
kind: Deployment
metadata:
  name: vite-frontend-deployment
  labels:
    app: vite-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vite-frontend
  template:
    metadata:
      labels:
        app: vite-frontend
    spec:
      containers:
      - name: vite-frontend
        image: vite-frontend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        workingDir: /vite-project/dist
        command: ["sh", "-c", "nginx -g 'daemon off;'"]
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1000m"
        envFrom:
          - configMapRef:
              name: vite-frontend-config