apiVersion: v1
kind: Service
metadata:
  name: vite-frontend-service
spec:
  type: NodePort
  selector:
    app: vite-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080